### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jwtoler** [tempusdominus/core#1]
When do you think you might have some basic documentation on how to import and render the modules?

**Comment by Eonasdan** [comment]
not sure. what would you like to see? in the mean time you can look at the bs4 module https://github.com/tempusdominus/bootstrap-4

**Comment by jwtoler** [comment]
I have actually tried looking at the too but I can not figure out how to implement the datetimepicker. I've tried `import DateTimePicker...` and `require(filename)`. I've then tried `new DateTimePicker();` in various different ways but nothing has worked. The module concept is something I'm still trying to pick up.

**Comment by Eonasdan** [comment]
Are you trying to create your own module or import the datepicker into your own code?

**Comment by jwtoler** [comment]
Import into my own code.
