### ISSUE TITLE
Remove dependency on jquery?

### ISSUE THREAD

**Issue by flexjoly** [tempusdominus/core#14]
Hi,

The doc say:
> This new version has been completely rewritten in ES6 and uses Babel to transpile the code down.

But jquery is still mentioned as a dependency. Is Tempusdominus using jquery still or is it just needed voor moment.js (and popper.js). 

Greetz, flexjoly

**Comment by marcusy3k** [comment]
Is jquery still needed?  I also want to know.

I really wish it does not need jquery.

**Comment by Eonasdan** [comment]
jquery zapping is going to be done in a new coming soon v6 over at eonasdan/tempus-dominus
