### ISSUE TITLE
Change DisabledTimeInterval on change.datetimepicker

### ISSUE THREAD

**Issue by dmasur** [tempusdominus/core#24]
Hi there,
i dont know if it fits here or on the boostrap4 repo that is use.

Problem:
I want to change the disabled time intervals for every selected date.

Current Outcome:
All hours are accepted after i changed a date.

Wanted Outcome:
The new interval is accepted and i cannot select the disabled times.

Here is a code example: https://jsfiddle.net/m6b0a8qf/1/

Thanks for the project and looking into this,
Dominik

**Comment by Eonasdan** [comment]
Going to be working on this picker again over at eonasdan/tempus-dominus. I'm going to merge td-core and td-bs4 together. No promises I can get this done, but you can open a new issues over there.
