### ISSUE TITLE
hide and show event not emit when date is null

### ISSUE THREAD

**Issue by cedk** [tempusdominus/core#30]
`_notifyEvent` does not emit those events when date and oldDate are null.
This is annoying if we want to plug to those events (for example we remove the overflow to make the popup fully visible).
I think for those 2 events it makes sense to emit with a null date.

**Comment by Eonasdan** [comment]
Going to be working on this picker again over at eonasdan/tempus-dominus. I'm going to merge td-core and td-bs4 together. No promises I can get this done, but you can open a new issues over there.
