### ISSUE TITLE
Locale does not change

### ISSUE THREAD

**Issue by balazs-zsoldos** [tempusdominus/core#4]
If I call

`myJqueryObj.datetimepicker('locale', newLocale)`

the texts in the popup calendar (e.g.: day names) do not change. Calling

`myJqueryObj.datetimepicker('format', newFormat)`

works, so I guess the problem is not in my code :).

Reproduced with tempusdominus-bootstrap-4 5.0.0-alpha9

**Comment by Eonasdan** [comment]
can you post a jsfiddle example or a demo somewhere
